### ISSUE TITLE
How can I create common "Hello, world!"?

### ISSUE THREAD

**Issue by Trimsku** [Panzerschrek/U-00DC-Sprache#8]
I try this:
```
type char8_ptr = $(char8);
fn nomangle printf(char8_ptr ptr) : void;
fn nomangle main() : i32  {
    printf("Hello, World!");    
    return 0;
}
```
I try to search something, about the common Hello world, but i didn't find anything.
Can you help me, please?
Is there "..." for function parameters in U-lang?

**Comment by Panzerschrek** [comment]
There are no functions with variable number of arguments in Ü.
String literals are not null-terminated, you need to add "\0" manually to pass string to C code.
String literal is just constant array. You need to obtain address of first element in order to pass it to _printf_ function.
Raw pointers are always mutable, so, you need also to use `cast_mut` to obtain raw pointer to string literal.

```
type char8_ptr = $(char8);
fn nomangle printf(char8_ptr str_null_terminated) unsafe : void;
fn nomangle main() : i32  {

    unsafe
    {
        printf($<(cast_mut("Hello, World!\n\0"[0])));
    }
    return 0;
}
```

**Comment by Trimsku** [comment]
Okey, thanks!
